title: Snoopy
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://kmu-seongukyun.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html


social:
  github: kmu-seongukyun
  email: seonugk3553@kookmin.ac.kr

google_analytics: "UA-214166996-1"

disqus:
    shortname: brianmaierjr
